GPT-2 Model Configuration

In [ ]:
GPT_CONFIG_124M = {
    "vocab_size": 50257,
    "context_length": 256,
    "stride": 128,
    "embedding_dim": 768,
    "num_layers": 12,
    "num_heads": 12,
    "dropout": 0.1,
    "qkv_bias": False
}

Load Dataset

In [3]:

file_path = "../the-verdict.txt"

with open(file_path, "r", encoding="utf-8") as file:
        text_data = file.read()

Tokenization

In [4]:
import tiktoken
import torch

tokenizer = tiktoken.get_encoding("gpt2")

In [5]:
token_ids = tokenizer.encode(text_data)

In [6]:
def text_to_token_ids(text, tokenizer):
    encoded = tokenizer.encode(text, allowed_special={'<|endoftext|>'})
    encoded_tensor = torch.tensor(encoded).unsqueeze(0) # add batch dimension
    return encoded_tensor

def token_ids_to_text(token_ids, tokenizer):
    flat = token_ids.squeeze(0) # remove batch dimension
    return tokenizer.decode(flat.tolist())

In [7]:
len(token_ids)

5145

Implementing Dataloader

In [8]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

class GPTDataset(Dataset):
    def __init__(self, text, tokenizer, max_len, stride):

        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(text)

        for i in range(0, len(token_ids) - max_len, stride):
            input_chunk = token_ids[i:i+max_len]
            target_chunk = token_ids[i+1:i+max_len+1]

            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))
    
    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, index):
        return self.input_ids[index], self.target_ids[index]
    
def create_dataloader(text, tokenizer, batch_size, context_len, stride, shuffle, drop_last, num_workers):

    dataset = GPTDataset(text, tokenizer, context_len, stride)

    dataloader = DataLoader(

        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers    
    )

    return dataloader

In [9]:
train_ratio = 0.8

train_data = text_data[:int(train_ratio*len(text_data))]
test_data = text_data[int(train_ratio*len(text_data)):]

torch.manual_seed(123)

train_dataloader = create_dataloader(

    text=train_data,
    tokenizer=tokenizer,
    batch_size=2,
    context_len=GPT_CONFIG_124M["context_length"],
    stride=GPT_CONFIG_124M["stride"],
    shuffle=True,
    drop_last=True,
    num_workers=0

)

test_dataloader = create_dataloader(
    
    text=test_data,
    tokenizer=tokenizer,
    batch_size=2,
    context_len=GPT_CONFIG_124M["context_length"],
    stride=GPT_CONFIG_124M["stride"],
    shuffle=False,
    drop_last=False,
    num_workers=0

)

In [10]:
for x, y in train_dataloader:
    print(x.shape, y.shape)

for x, y in test_dataloader:
    print(x.shape, y.shape)

torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([1, 256]) torch.Size([1, 256])

Multi-Head Attention

In [11]:
class MultiHeadAttention(nn.Module):

    def __init__(self, d_in, d_out, num_heads, context_len, dropout, qkv_bias):
        super().__init__()

        assert(d_out % num_heads ==0), "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = (d_out // num_heads)

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.out_proj = nn.Linear(d_out, d_out)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_len, context_len), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape

        queries = self.W_query(x)
        keys = self.W_key(x)
        values = self.W_value(x)

        # print("Keys:")
        # print(keys)

        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)

        # print(queries)
        
        # print(values)

        queries = queries.transpose(1, 2)
        keys = keys.transpose(1, 2)
        values = values.transpose(1, 2)

        attn_score = queries @ keys.transpose(2, 3)
        # print(attn_score)
        
        masked_bool = self.mask.bool()[:num_tokens, :num_tokens]

        attn_score.masked_fill_(masked_bool, -torch.inf)
        # print(attn_score)

        attn_weights = torch.softmax(attn_score / (keys.shape[-1] ** 0.5), dim=-1)
        attn_weights = self.dropout(attn_weights)
        # print(attn_weights)

        context_vector = attn_weights @ values
        context_vector = context_vector.transpose(1, 2)

        context_vector = context_vector.contiguous().view(b, num_tokens, self.d_out)
        context_vector = self.out_proj(context_vector)
        # print(context_vector)

        return context_vector

Layer Normalization, GELU Activation Function and Feed Forward Neural Network

In [12]:
class LayerNormaliztion(nn.Module):

    def __init__(self, emb_dim):
        super().__init__()

        self.eps = 1e-5
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))

    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = x.var(dim=-1, keepdim=True)
        x_norm = (x - mean)/torch.sqrt(var + self.eps)
        # print(x_norm)

        return self.scale * x_norm + self.shift


class GELUActivation(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 0.5 * x * (1 + torch.tanh(
            torch.sqrt(torch.tensor(2.0 / torch.pi)) *
            (x + 0.044715 * torch.pow(x, 3))
        ))
    
class FeedForward(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(cfg["embedding_dim"], 4*cfg["embedding_dim"]),
            GELUActivation(),
            nn.Linear(4*cfg["embedding_dim"], cfg["embedding_dim"])

        )
        
    def forward(self, x):
        return self.layers(x)

Transformer Block

In [13]:
class TransformerBlock(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.attention = MultiHeadAttention(
            d_in=cfg["embedding_dim"],
            d_out=cfg["embedding_dim"],
            num_heads=cfg["num_heads"],
            context_len=cfg["context_length"],
            dropout=cfg["dropout"],
            qkv_bias=cfg["qkv_bias"]
        )

        self.norm1 = LayerNormaliztion(cfg["embedding_dim"])
        self.norm2 = LayerNormaliztion(cfg["embedding_dim"])
        self.ff = FeedForward(cfg)
        self.dropout = nn.Dropout(cfg["dropout"])
    
    def forward(self, x):
        shortcut = x
        x = self.norm1(x)
        x = self.attention(x)
        x = self.dropout(x)
        x = x + shortcut
        # print(x)

        shortcut = x
        x = self.norm2(x)
        x = self.ff(x)
        x = self.dropout(x)
        x = x + shortcut

        return x

GPT Model Architecture

In [14]:
class GPTModel(nn.Module):
    def __init__(self, cfg):
        super().__init__()

        self.tok_emb = nn.Embedding(cfg["vocab_size"], cfg["embedding_dim"])
        self.pos_emb = nn.Embedding(cfg["context_length"], cfg["embedding_dim"])
        self.dropout = nn.Dropout(cfg["dropout"])

        self.transformers = nn.Sequential(
            *[TransformerBlock(cfg) for _ in range(cfg["num_layers"])]
        )

        self.final_norm = LayerNormaliztion(cfg["embedding_dim"])
        self.final_output = nn.Linear(cfg["embedding_dim"], cfg["vocab_size"], bias=False)

    def forward(self, in_idx):
        batch_size, seq_len = in_idx.shape

        tok_emb = self.tok_emb(in_idx)
        pos_emb = self.pos_emb(torch.arange(seq_len, device=in_idx.device))
        x = tok_emb + pos_emb
        x = self.dropout(x)
        # print("Token Embeddings")
        # print(tok_emb)

        x = self.transformers(x)
        # print(x)

        x = self.final_norm(x)
        logits = self.final_output(x)

        return logits
torch.manual_seed(123)
model = GPTModel(GPT_CONFIG_124M)
model.eval();

Loss Function

In [15]:
def calc_loss_batch(input_batch, target_batch, model, device):
    input_batch, target_batch = input_batch.to(device), target_batch.to(device)
    logits = model(input_batch)
    # print(logits)
    loss = torch.nn.functional.cross_entropy(logits.flatten(0, 1), target_batch.flatten())
    # print(loss)
    return loss


def calc_loss_loader(data_loader, model, device, num_batches=None):
    total_loss = 0.
    
    if len(data_loader) == 0:
        return float("nan")
    elif num_batches is None:
        num_batches = len(data_loader)
    else:
        # Reduce the number of batches to match the total number of batches in the data loader
        # if num_batches exceeds the number of batches in the data loader
        num_batches = min(num_batches, len(data_loader))
    for i, (input_batch, target_batch) in enumerate(data_loader):
        if i < num_batches:
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            total_loss += loss.item()
        else:
            break
    return total_loss / num_batches

In [16]:
def evaluate_model(model, train_loader, test_loader, device, eval_iter):
    model.eval()
    with torch.no_grad():
        train_loss = calc_loss_loader(train_loader, model, device, num_batches=eval_iter)
        val_loss = calc_loss_loader(test_loader, model, device, num_batches=eval_iter)
    model.train()
    return train_loss, val_loss

Training Loop for LLM

In [17]:
def train_model(model, train_loader, test_loader, optimizer, device, num_epochs, eval_freq, eval_iter):
    train_losses, test_losses, track_tokens_seen = [], [], []
    tokens_seen, global_step = 0, -1

    for epoch in range(num_epochs):
        print(f"Epoch: {epoch + 1}")
        model.train()

        for input_batch, target_batch in train_loader:
            optimizer.zero_grad()
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            loss.backward()
            optimizer.step()
            tokens_seen = tokens_seen + input_batch.numel()
            global_step += 1

            if(global_step % eval_freq ==0):
                train_loss, test_loss = evaluate_model(model, train_loader, test_loader, device, eval_iter)

                train_losses.append(train_loss)
                test_losses.append(test_loss)
                track_tokens_seen.append(tokens_seen)

                print(f"Ep {epoch+1} (Step {global_step:06d}): "
                      f"Train loss {train_loss:.3f}, Test loss {test_loss:.3f}")
                
        
        
    
    return train_losses, test_losses, track_tokens_seen

In [18]:
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

In [19]:
print(torch.cuda.memory_allocated()/1024**3, "GB allocated")
print(torch.cuda.memory_reserved()/1024**3, "GB reserved")

0.0 GB allocated
0.0 GB reserved

In [20]:
import time
start_time = time.time()

gpu = torch.device('cuda')
torch.manual_seed(123)
model = GPTModel(GPT_CONFIG_124M)



model.to(gpu)
optimizer = torch.optim.AdamW(model.parameters(), lr = 0.0004, weight_decay=0.1)

num_epochs = 10

train_losses, test_losses, tokens_seen = train_model(
    model, train_dataloader, test_dataloader, optimizer, gpu, num_epochs, eval_freq=5, eval_iter=5
)

end_time = time.time()

time_taken = (end_time - start_time)/60

print(f"Time Taken for Training in minutes: {time_taken} Minutes")

Epoch: 1
Ep 1 (Step 000000): Train loss 9.980, Test loss 10.076
Ep 1 (Step 000005): Train loss 8.169, Test loss 8.493
Ep 1 (Step 000010): Train loss 6.793, Test loss 7.322
Epoch: 2
Ep 2 (Step 000015): Train loss 6.154, Test loss 6.950
Ep 2 (Step 000020): Train loss 5.885, Test loss 6.841
Ep 2 (Step 000025): Train loss 5.655, Test loss 6.852
Epoch: 3
Ep 3 (Step 000030): Train loss 5.313, Test loss 6.771
Ep 3 (Step 000035): Train loss 5.009, Test loss 6.746
Ep 3 (Step 000040): Train loss 5.153, Test loss 6.785
Epoch: 4
Ep 4 (Step 000045): Train loss 4.738, Test loss 6.604
Ep 4 (Step 000050): Train loss 4.212, Test loss 6.608
Ep 4 (Step 000055): Train loss 3.854, Test loss 6.589
Epoch: 5
Ep 5 (Step 000060): Train loss 3.265, Test loss 6.510
Ep 5 (Step 000065): Train loss 2.955, Test loss 6.524
Ep 5 (Step 000070): Train loss 2.383, Test loss 6.536
Epoch: 6
Ep 6 (Step 000075): Train loss 2.240, Test loss 6.565
Ep 6 (Step 000080): Train loss 1.799, Test loss 6.647
Ep 6 (Step 000085): Train loss 1.709, Test loss 6.668
Epoch: 7
Ep 7 (Step 000090): Train loss 1.440, Test loss 6.699
Ep 7 (Step 000095): Train loss 1.213, Test loss 6.806
Ep 7 (Step 000100): Train loss 0.965, Test loss 6.850
Epoch: 8
Ep 8 (Step 000105): Train loss 0.813, Test loss 6.862
Ep 8 (Step 000110): Train loss 0.678, Test loss 6.954
Ep 8 (Step 000115): Train loss 0.581, Test loss 7.009
Epoch: 9
Ep 9 (Step 000120): Train loss 0.535, Test loss 7.102
Ep 9 (Step 000125): Train loss 0.401, Test loss 7.132
Ep 9 (Step 000130): Train loss 0.359, Test loss 7.254
Epoch: 10
Ep 10 (Step 000135): Train loss 0.336, Test loss 7.277
Ep 10 (Step 000140): Train loss 0.300, Test loss 7.407
Ep 10 (Step 000145): Train loss 0.204, Test loss 7.423
Time Taken for Training in minutes: 0.4775100310643514 Minutes

Generate Text Function

In [21]:
def generate_text(model, idx, max_new_tokens, context_len, temperature=0.0, topk=None, eos_id=None):

    for _ in range(max_new_tokens):

        idx = idx.to(gpu)
        idx_cond = idx[:, -context_len:]
        

        with torch.no_grad():
            logits = model(idx_cond)
        logits = logits[:, -1, :]

        if topk is not None:
            top_logits, _ = torch.topk(logits, topk)
            min_val = top_logits[:, -1]
            logits = torch.where(logits < min_val, torch.tensor(float("-inf")).to(logits.device), logits)

        if temperature > 0.0:
            logits = logits/temperature
            probs = torch.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
        
        else:
            probs = torch.softmax(logits, dim=-1)
            idx_next = torch.argmax(probs, dim=-1, keepdim=True)
        
        if eos_id == idx_next:
            break
        
        idx = torch.cat((idx, idx_next), dim=1)

    return idx

In [22]:
token_ids = generate_text(
    model = model,
    idx = text_to_token_ids("Every Effort Moves You", tokenizer),
    max_new_tokens=20,
    context_len=GPT_CONFIG_124M["context_length"],
    temperature=1.5,
    topk=50

)

print("Output Text: \n", token_ids_to_text(token_ids, tokenizer))

Output Text:
 Every Effort Moves You lucky You him better; for he rose from the fact with equanimity.
She Arrt

Import Tensorflow

In [24]:
import tensorflow as tf
import tqdm

Download Pretrained Weights from OpenAI

In [25]:
from gpt_download3 import download_and_load_gpt2

In [26]:
settings, params = download_and_load_gpt2(model_size="124M", models_dir="gpt2")

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/checkpoint

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/encoder.json

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/hparams.json

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/model.ckpt.data-00000-of-00001

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/model.ckpt.index

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/model.ckpt.meta

/home/iztihad/Documents/GPT_2_from_scratch/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openaipublic.blob.core.windows.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File already exists and is up-to-date: gpt2/124M/vocab.bpe

In [27]:
print(f"Settings: {settings}")
print(f"Params Dictionary Keys: {params.keys()}")

Settings: {'n_vocab': 50257, 'n_ctx': 1024, 'n_embd': 768, 'n_head': 12, 'n_layer': 12}
Params Dictionary Keys: dict_keys(['blocks', 'b', 'g', 'wpe', 'wte'])

In [28]:

NEW_CONFIG_GPT_2 = GPT_CONFIG_124M.copy()
NEW_CONFIG_GPT_2.update({"context_length": 1024, "qkv_bias": True})
print(NEW_CONFIG_GPT_2)

{'vocab_size': 50257, 'context_length': 1024, 'stride': 128, 'embedding_dim': 768, 'num_layers': 12, 'num_heads': 12, 'dropout': 0.1, 'qkv_bias': True}

In [29]:
gpt = GPTModel(NEW_CONFIG_GPT_2)
gpt.eval()

GPTModel(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(1024, 768)
  (dropout): Dropout(p=0.1, inplace=False)
  (transformers): Sequential(
    (0): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (1): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (2): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (3): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (4): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (5): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (6): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (7): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (8): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (9): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (10): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (11): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (final_norm): LayerNormaliztion()
  (final_output): Linear(in_features=768, out_features=50257, bias=False)
)

In [30]:
model.eval()

GPTModel(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(256, 768)
  (dropout): Dropout(p=0.1, inplace=False)
  (transformers): Sequential(
    (0): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (1): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (2): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (3): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (4): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (5): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (6): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (7): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (8): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (9): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (10): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (11): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (final_norm): LayerNormaliztion()
  (final_output): Linear(in_features=768, out_features=50257, bias=False)
)

Updating the weights of our model with the downloaded weights from OpenAI

In [31]:
def assign(left, right):
    
    if left.shape != right.shape:
        raise ValueError(f"Shape mismatch. Left: {left.shape}, Right: {right.shape}")
    return torch.nn.Parameter(torch.tensor(right))

In [32]:
print(params["blocks"][0])

{'attn': {'c_attn': {'b': array([ 0.48033914, -0.5254326 , -0.42926455, ...,  0.01257301,
       -0.04987717,  0.00324764], shape=(2304,), dtype=float32), 'w': array([[-0.4738484 , -0.26136586, -0.09780374, ...,  0.05132535,
        -0.0584389 ,  0.02499568],
       [ 0.08742206,  0.1473427 ,  0.23870145, ..., -0.05253514,
        -0.01125987, -0.01558759],
       [ 0.00388936,  0.06946629,  0.3668052 , ...,  0.11428114,
         0.03629516, -0.03184864],
       ...,
       [-0.25919554, -0.01636625,  0.19914557, ...,  0.00953369,
        -0.05159837,  0.03186192],
       [ 0.15165617,  0.2170211 ,  0.10434178, ...,  0.02933884,
        -0.04287174, -0.04746685],
       [-0.41001597, -0.19235404, -0.2400296 , ..., -0.00459218,
         0.00697855,  0.01984419]], shape=(768, 2304), dtype=float32)}, 'c_proj': {'b': array([ 1.50291592e-01, -1.54261470e-01, -1.46630690e-01, -9.91277322e-02,
        3.38026471e-02, -3.44475470e-02, -7.06353709e-02, -9.36073363e-02,
        8.11094940e-02,  3.11609730e-02, -1.99268594e-01, -3.72450203e-02,
        3.04950611e-03,  4.98915873e-02, -5.35597987e-02,  3.74077745e-02,
       -1.90889344e-01, -8.15392509e-02,  4.91158701e-02,  1.41873658e-01,
       -1.12115644e-01, -9.67213959e-02,  5.31062596e-02, -2.18802363e-01,
        9.35775712e-02,  1.21672889e-02,  1.21633019e-02,  8.57575163e-02,
        4.57975380e-02,  5.81334829e-02,  9.50638354e-02, -4.79569584e-02,
        8.81402865e-02, -3.36610749e-02, -5.01198471e-02, -9.27842781e-02,
        8.16035829e-03, -2.32866239e-02, -2.03313380e-02,  3.15182693e-02,
       -3.75814289e-02,  1.48433819e-01,  1.52457207e-01,  4.55480143e-02,
        4.08164591e-01,  1.10435961e-02,  5.16626462e-02,  1.23723790e-01,
        1.20229915e-01,  2.44907364e-02,  1.10535897e-01,  4.62413281e-02,
        3.69316638e-02,  1.90547854e-02, -3.05058230e-02,  3.34868580e-01,
        1.01866893e-01,  1.51844040e-01, -3.55911180e-02, -2.78632134e-01,
        1.04952365e-01,  1.12033576e-01, -1.04038261e-01, -9.27677676e-02,
       -1.83252048e+00, -5.45688644e-02, -2.04300098e-02,  8.84775147e-02,
       -6.21197512e-03, -5.02327308e-02,  5.49565144e-02,  9.08352286e-02,
        5.65262251e-02, -3.57958227e-02,  2.39251833e-02,  4.45792153e-02,
        1.69097647e-01,  1.79229286e-02, -1.08360253e-01, -5.69820143e-02,
       -2.28381082e-01, -1.00048050e-01,  7.17396988e-03, -6.09117141e-03,
       -1.12976450e-02, -7.75404125e-02, -2.80990809e-01, -2.19064260e+00,
        4.35759500e-03,  9.96193886e-02, -4.19126227e-02, -5.37094586e-02,
        4.68911119e-02, -1.32178981e-02, -3.64953605e-03, -2.16684919e-02,
       -1.47190854e-01,  4.24816599e-03,  9.13177356e-02,  1.19620403e-02,
        8.20969511e-03,  1.04284704e+00, -2.02548574e-03, -9.08735842e-02,
       -8.69176611e-02,  2.79114838e-03,  1.39157881e-03, -1.08542301e-01,
       -1.59905180e-02,  4.26262282e-02,  3.92578900e-01, -2.60494631e-02,
       -4.78280112e-02, -2.90739108e-02,  2.32299902e-02, -1.17224135e-01,
        4.18439414e-03,  1.09014541e-01, -4.29131091e-02, -4.06361036e-02,
        2.15819255e-02, -4.69887666e-02, -5.95416650e-02, -1.04264937e-01,
        7.10679218e-02,  3.65232453e-02, -1.58147831e-02, -8.74658450e-02,
       -1.75946355e-02,  1.97625577e-01, -3.30342799e-02, -7.48701906e-03,
       -3.94917615e-02, -9.73603595e-03,  3.25740315e-02,  3.72396410e-02,
       -6.70865295e-04, -3.26125622e-02, -2.01131292e-02, -2.72057593e-01,
        6.10516146e-02, -7.95367584e-02,  1.91656277e-01,  3.32605205e-02,
       -1.94583219e-02, -1.46382228e-02,  3.22325043e-02,  2.08338480e-02,
       -4.38788682e-02, -2.25119889e-01, -2.04798509e-03,  2.88150758e-01,
        1.92447290e-01,  1.33934021e-01,  6.39288351e-02, -6.05820026e-03,
       -1.03858508e-01,  2.10598968e-02,  1.49405999e-02, -6.73835799e-02,
        1.61145344e-01, -7.85959959e-02,  1.83188040e-02,  3.39911357e-02,
       -8.61307979e-03, -5.81252798e-02,  3.16176042e-02, -4.34091300e-01,
       -3.90117504e-02,  1.23895347e-01, -5.65045979e-03,  1.39109462e-01,
        8.30941722e-02, -6.00043908e-02,  5.01748621e-02, -7.67613128e-02,
       -1.37089357e-01, -2.89400090e-02,  3.92793156e-02, -9.11396742e-02,
       -5.96550293e-02, -5.90233877e-03,  6.19329102e-02,  2.81360187e-02,
        3.71572301e-02, -7.91418180e-02, -3.01448293e-02, -4.04244035e-01,
        5.40463738e-02, -8.96997154e-02, -7.30845630e-02,  1.54693499e-01,
       -7.58425295e-02,  8.95922408e-02,  2.19247565e-02, -1.94200948e-01,
        4.27287780e-02,  1.50333360e-01, -4.50464524e-02, -5.10406531e-02,
        1.05322480e-01,  7.46112242e-02,  2.89416425e-02,  2.94055138e-02,
       -8.89807045e-02,  5.87626547e-02, -3.08654755e-02,  3.30361128e-02,
        1.44937158e-01, -3.76457237e-02,  3.17093544e-02, -5.73333763e-02,
        7.13309869e-02,  1.61310002e-01, -6.76055253e-02,  2.65316647e-02,
        1.71000231e-02,  2.67168097e-02, -3.52318794e-01, -1.86412409e-02,
        9.39103216e-02,  4.27322015e-02,  5.29620908e-02, -4.77100462e-02,
       -2.44526640e-01,  4.72296290e-02,  1.71168949e-02, -8.71210098e-02,
        3.61558683e-02, -9.78822485e-02,  4.60202154e-03, -5.56314513e-02,
       -1.12519503e-01,  2.72571985e-02, -4.91369888e-02, -3.88996191e-02,
       -2.30957810e-02, -4.77664284e-02,  9.20729339e-02, -4.43887785e-02,
        9.94134620e-02,  3.37515175e-02, -7.82610476e-02, -4.53337096e-02,
        5.50654111e-03, -6.45809248e-02, -5.80331385e-02,  2.44406074e-01,
       -6.48254156e-02, -2.91666947e-02,  2.14915216e-01,  5.05455164e-03,
       -4.99597788e-02, -1.37186348e-01, -9.83577073e-02, -4.40529883e-02,
        5.66545874e-02,  1.95001513e-02,  7.10280687e-02, -1.23177804e-01,
       -6.75908756e-03, -1.63850382e-01, -2.95621082e-02, -2.55707204e-02,
        6.46771565e-02,  1.24140203e-01, -2.88983911e-01,  1.85427461e-02,
       -4.94092843e-03, -2.28420720e-02, -5.82439482e-01,  1.59630567e-01,
       -4.15058322e-02, -1.36789292e-01, -3.52913365e-02, -8.39222372e-02,
        7.86174759e-02, -7.28819296e-02,  2.60765329e-02,  6.53795227e-02,
       -4.62115817e-02, -7.76968673e-02, -5.87572195e-02, -1.30361229e-01,
        3.78489010e-02,  6.55296594e-02,  5.25620067e-04,  3.84496264e-02,
        1.24320388e+00, -1.68723464e-01, -4.86641787e-02,  6.50869384e-02,
       -1.47681460e-02,  2.14988664e-02, -5.95275797e-02,  7.27598369e-02,
       -2.76989024e-02,  3.05728242e-02,  1.12622999e-01, -6.53531263e-03,
        1.30190837e+00, -6.84213266e-02,  7.51543865e-02, -1.45101603e-02,
        9.05745327e-02,  3.10498103e-02, -9.33986995e-03, -4.21756506e-02,
        2.72210330e-01, -1.27303945e-02, -2.81840190e-02, -2.60730118e-01,
       -3.90493893e-04,  5.62561341e-02,  3.72812040e-02, -1.11589909e-01,
        3.20615396e-02, -7.30896816e-02, -1.37190655e-01, -1.93495583e-02,
        1.09623618e-01,  4.89381962e-02,  4.03108783e-02,  5.66774234e-02,
        1.62189886e-01,  3.46248299e-02,  1.98779011e+00, -4.22412790e-02,
       -5.13165304e-03,  2.71435119e-02,  1.85617842e-02, -1.61900406e-03,
        7.35084414e-02, -1.80124324e-02,  4.54520956e-02,  2.73929369e-02,
        7.67490687e-03, -2.27434468e-03, -1.07111521e-01, -6.20795079e-02,
       -4.25037667e-02,  2.89389351e-03, -1.93578806e-02,  2.14844160e-02,
        1.02155335e-01, -2.28438266e-02, -8.82948842e-03,  5.34855239e-02,
        1.32491542e-02, -1.93692967e-01, -2.21208688e-02, -6.07637241e-02,
       -1.41583674e-03, -5.75221237e-03,  2.96317600e-02,  9.59862992e-02,
       -5.20756900e-01,  3.05425655e-02,  4.27237600e-02, -1.05623081e-02,
        2.80843470e-02, -2.15309989e-02, -1.14986822e-01, -4.64756899e-02,
        1.74023844e-02,  5.18818051e-02,  8.61238781e-03,  2.50723809e-02,
        6.04280867e-02,  3.79306599e-02,  7.69275203e-02,  4.40698117e-02,
       -5.48095778e-02, -1.79662549e+00,  7.54253045e-02, -7.82284215e-02,
       -4.49145958e-02,  1.09757118e-01,  2.43218280e-02,  4.12850864e-02,
       -3.74493487e-02,  1.44195154e-01, -1.09265909e-01,  5.99483609e-01,
       -1.48811057e-01,  1.63515806e-01,  2.01536313e-01,  3.50999460e-02,
       -4.77274582e-02,  4.34552059e-02, -1.24818766e-02,  7.75491893e-02,
        7.36957192e-02,  1.07473505e+00,  1.56118255e-02, -3.98723856e-02,
       -1.99026894e-03, -2.67302268e-03,  1.09987129e-02, -8.31420794e-02,
        1.60791706e-02,  5.24520129e-02,  1.09885357e-01, -6.81176633e-02,
       -2.03685984e-02, -2.02950276e-02, -1.31701976e-02, -4.41238545e-02,
       -1.86516330e-01,  2.63172667e-02, -6.12686984e-02,  2.73441616e-02,
        5.35953753e-02, -5.94596751e-02,  3.90319705e-01,  1.58265874e-01,
       -6.51728883e-02, -9.37114805e-02, -3.04794908e-01,  1.78403948e-02,
       -4.21562493e-01,  1.79814890e-01, -4.19822484e-02,  1.07999131e-01,
       -1.12285861e-03, -7.40313996e-03,  3.46018225e-02,  9.94060710e-02,
       -2.12973967e-01,  1.83927473e-02, -1.14071012e-01,  2.09030509e-01,
        1.74317345e-01,  5.07600047e-02, -7.99916014e-02, -1.03533134e-01,
       -1.04002237e-01, -8.12925175e-02,  3.48921865e-01, -7.23054335e-02,
       -1.63415521e-02,  1.08868554e-01, -1.11544169e-01, -1.70933470e-01,
       -7.69036934e-02, -5.33608794e-02, -6.74895123e-02,  2.03031635e+00,
        6.45208987e-04, -6.95536062e-02, -1.38247386e-03, -2.14724578e-02,
       -1.20527798e-03,  4.51721177e-02, -7.95379728e-02,  2.19162241e-01,
       -5.68107329e-02,  5.93782961e-02, -2.91723032e-02,  6.37570098e-02,
        7.10485950e-02,  1.16237246e-01,  2.43401993e-02,  2.77571362e-02,
        5.66851079e-01,  3.64834517e-02,  4.01598625e-02,  5.05386405e-02,
       -4.83381413e-02,  5.06714657e-02,  3.16178501e-02, -5.19339778e-02,
        2.06955820e-02, -7.72106722e-02,  7.94691369e-02, -6.32428303e-02,
       -3.73780131e-02, -2.11108588e-02,  6.31993786e-02,  1.73402697e-01,
       -2.52057648e+00,  2.11770475e-01,  2.84188353e-02,  6.44935444e-02,
        8.04665238e-02,  2.29352899e-02, -6.16367608e-02, -1.19411238e-01,
        1.33787394e-01,  5.81165403e-02,  3.48466821e-02,  1.70425382e-02,
        3.50110829e-02,  5.67671098e-03,  4.08529453e-02, -6.06861673e-02,
        7.82610178e-02,  3.19457263e-01, -1.23103566e-01,  5.48298024e-02,
        4.51117121e-02,  5.20399548e-02, -8.53389800e-02, -1.34841651e-01,
       -1.93401109e-02,  1.31341398e-01,  7.32930452e-02,  3.42762060e-02,
       -2.30766702e-02, -4.58635315e-02, -5.00986949e-02,  1.05671950e-01,
       -7.59337842e-01, -5.75660281e-02,  5.55198640e-02,  1.64293781e-01,
        3.63187902e-02,  2.84902453e-01, -4.55541685e-02, -8.17313092e-04,
       -9.22120735e-02, -6.47155643e-02,  3.70488651e-02, -5.72381401e-03,
       -2.54315659e-02,  6.68617859e-02, -6.42634392e-01, -3.15013132e-03,
       -2.05270976e-01,  2.19443114e-03, -2.09804680e-02, -9.16424245e-02,
       -3.00870147e-02,  8.17643031e-02,  9.82891098e-02, -9.05914903e-02,
       -2.41509527e-02, -4.93184216e-02,  1.51200861e-01,  1.26610935e-01,
        2.07586721e-01, -4.65210900e-02, -3.72777507e-02,  7.96492994e-02,
        9.89030823e-02,  1.51725158e-01, -2.07502376e-02,  1.52699845e-02,
        1.11505866e-01, -2.19635181e-02,  3.00890449e-02,  7.20896870e-02,
       -4.31517214e-02, -8.00602883e-02, -8.04479063e-01,  9.11372975e-02,
        4.02164161e-02,  1.15437731e-01,  2.59815678e-02,  2.77805686e-01,
        3.31278108e-02, -9.27837789e-02, -3.37601118e-02,  8.58945176e-02,
        3.67445722e-02,  1.43809423e-01,  7.23938122e-02, -9.89423785e-03,
        6.46558627e-02,  6.06056191e-02, -9.32627171e-02,  2.28204187e-02,
        6.74316734e-02, -4.45092544e-02, -7.92841893e-03,  1.03168242e-01,
        7.01951832e-02,  7.05947876e-02, -2.02797905e-01, -6.10490702e-02,
       -1.03977673e-01,  2.01638535e-01,  6.38528615e-02,  1.39080817e-02,
       -9.11322236e-02, -1.74816009e-02,  6.41126558e-02,  6.52194992e-02,
       -1.86735123e-01,  2.28622649e-02,  3.21862008e-03,  3.52379978e-02,
       -8.94155726e-02, -2.10108534e-01, -9.00387987e-02, -5.66195510e-02,
       -9.94458646e-02, -1.46827670e-02,  3.98572721e-02,  1.10109942e-02,
        1.72099292e-01,  4.66704257e-02, -5.62974205e-03, -1.90084651e-01,
        1.32802919e-01, -3.20305169e-01, -1.49562284e-02, -7.71356607e-03,
        1.29080534e-01, -4.38310839e-02,  2.12840270e-02, -1.04566298e-01,
       -1.44297238e-02,  5.75511456e-02, -9.32566896e-02,  1.92275986e-01,
       -7.72481188e-02, -8.90227705e-02,  4.24076580e-02,  2.29949970e-02,
       -1.90783269e-03, -2.24433076e-02,  2.86288466e-02, -4.50974017e-01,
       -9.35303271e-02, -3.12224589e-02, -6.05539307e-02, -3.89822215e-01,
        1.82790346e-02, -6.51681274e-02, -1.13358781e-01,  1.30122215e-01,
       -8.87142271e-02,  1.11566491e-01,  3.03425752e-02, -4.82597262e-01,
       -2.71061230e-02,  1.96380690e-02, -5.95935620e-02,  1.43620931e-02,
        3.18661392e-01, -5.94996922e-02, -2.58990258e-01, -7.79647231e-02,
       -1.24040306e-01,  1.00334875e-01,  7.58316219e-02,  1.36931717e-01,
       -9.90070105e-02, -1.02476902e-01, -8.52138028e-02,  7.99705684e-02,
       -1.19947411e-01,  6.80758506e-02, -4.17040847e-03, -9.72047374e-02,
       -3.74268182e-02,  1.04865395e-01, -4.35258560e-02, -7.90128633e-02,
       -1.22383803e-01, -2.66995635e-02,  2.12893356e-02,  6.22714907e-02,
        6.82306476e-03,  8.88071656e-02,  3.48808207e-02,  2.14223675e-02,
       -6.76893815e-02,  6.69644354e-03,  4.07648534e-01, -2.88482830e-02,
        1.27005288e-02,  9.04358923e-03, -6.83280885e-01,  6.36659469e-03,
       -6.67876154e-02,  1.14090785e-01, -3.97175960e-02,  1.70660496e-01,
       -1.17463134e-01,  1.05634883e-01,  7.33969957e-02, -3.47901904e-03,
        7.45378509e-02, -3.85625809e-01, -4.48852256e-02,  3.06252483e-02,
        9.00788978e-03,  2.87413932e-02, -6.99831396e-02,  6.47244528e-02,
       -1.53484633e-02, -7.73354620e-02, -4.89282385e-02, -6.90906420e-02,
       -2.93730013e-02, -3.07472758e-02, -1.08461291e-01, -1.78203769e-02,
       -1.12080298e-01, -3.03875725e-03,  2.48013083e-02,  3.02789539e-01,
       -5.28458692e-03, -9.94251147e-02,  1.64984509e-01, -5.83443232e-02,
        9.93507802e-02,  6.35922700e-02,  1.38438314e-01, -1.33376112e-02,
       -5.68705387e-02, -7.54863098e-02, -4.56717610e-02,  5.62873809e-03,
        1.81772932e-02, -6.95235375e-03,  6.35632873e-02,  3.17528173e-02,
        4.58365053e-01,  1.41986519e-01, -2.33734474e-02, -1.33302659e-01,
        2.80268312e-01,  1.05439164e-02,  1.11037875e-02,  8.92819613e-02,
       -9.19805653e-03,  3.25669795e-02,  9.26340073e-02,  1.89741049e-02,
       -6.62625115e-03, -1.13807894e-01, -2.68316995e-02,  1.01224199e-01,
        4.71617095e-02,  5.73493652e-02,  3.44568044e-02, -8.78939703e-02,
       -3.42216194e-02,  8.21585134e-02,  2.16742426e-01, -2.23023854e-02,
        4.05435897e-02, -9.32932973e-01, -1.16517171e-02, -1.42098725e-01,
       -1.08968101e-01,  5.71077503e-02,  3.39404331e-04,  2.10285783e-01,
        1.57134309e-02, -7.95061812e-02, -7.27630928e-02,  7.60467499e-02,
       -2.68441582e+00, -4.51369435e-01, -3.12863402e-02, -1.05210707e-01,
        4.55858074e-02, -4.64431681e-02, -5.21949567e-02, -3.89068834e-02,
       -4.07778397e-02,  1.22158013e-01, -1.32018365e-02,  2.83080563e-02],
      dtype=float32), 'w': array([[ 0.31271818, -0.18741347,  0.09802487, ..., -0.01197052,
         0.00937042, -0.03094269],
       [-0.2441914 , -0.19776976, -0.10981242, ..., -0.01619207,
         0.0250126 ,  0.04585942],
       [-0.4300631 ,  0.15438755,  0.05378212, ...,  0.0143031 ,
        -0.01807742, -0.001585  ],
       ...,
       [ 0.02024095,  0.19843437, -0.14822172, ...,  0.02351136,
         0.01069828, -0.01499684],
       [ 0.01707203,  0.02523554, -0.01841385, ..., -0.00083186,
         0.00859382,  0.00495879],
       [-0.10107431, -0.07349669, -0.00237457, ...,  0.00625391,
         0.01317109, -0.01713555]], shape=(768, 768), dtype=float32)}}, 'ln_1': {'b': array([-3.67732509e-03,  2.71967370e-02, -6.40409067e-02, -4.96289041e-03,
       -1.56569183e-02, -1.14681730e-02,  2.01928690e-01,  3.57880071e-02,
       -2.00533448e-03, -8.16634391e-03, -5.58354566e-03, -2.33619078e-03,
        5.69482159e-04, -7.21960794e-03, -3.01143397e-02,  1.48126169e-03,
       -9.41331126e-03, -1.41943945e-03, -1.30579779e-02, -5.28269373e-02,
        1.76632509e-03,  6.81459438e-04, -2.01510172e-03, -1.61979143e-02,
       -1.85251758e-02,  8.22157381e-05, -1.30996043e-02, -1.08058490e-02,
       -8.07740446e-03, -7.51511753e-03, -3.72523628e-03,  1.63655151e-02,
       -1.49062527e-02, -3.38537572e-03, -1.38868543e-03, -3.73382233e-02,
        4.70298231e-02, -5.93411410e-03, -9.15681385e-03,  1.48414019e-02,
       -6.53096614e-03, -2.55890260e-03, -8.83578602e-03,  9.10734944e-03,
       -1.56846307e-02, -7.10332126e-04, -2.77512288e-03, -3.53861251e-04,
       -4.49653435e-03, -1.24863153e-02, -8.76057148e-03,  3.18984035e-03,
       -3.52238230e-02, -6.69947267e-03, -3.45130306e-04,  5.87358465e-03,
       -9.63717233e-03, -1.71478242e-02, -4.66636242e-03, -1.59809962e-02,
        2.06960645e-03, -6.71303924e-03,  2.39331163e-02, -4.95314635e-02,
        1.45099554e-02, -4.55453992e-03, -6.39451682e-05,  8.02837834e-02,
       -5.54826260e-02,  3.05132964e-03, -6.08656835e-03, -2.62830257e-02,
       -1.11990012e-02, -1.53897116e-02, -1.14745656e-02, -1.25129567e-02,
       -8.42235144e-03, -1.46121413e-01, -3.57431360e-03, -1.96448471e-02,
       -4.42225439e-03, -4.00066230e-04, -2.24305317e-03, -1.29711935e-02,
       -4.32157591e-02,  2.52039526e-02,  6.35838732e-02,  1.41269630e-02,
       -1.26700271e-02, -3.61766201e-03, -4.53761080e-03, -7.54968403e-03,
       -6.29423261e-02, -7.91836996e-03, -6.45693066e-03,  1.56632450e-03,
        3.77798826e-03,  1.44509494e-03, -1.73853897e-02, -8.78879149e-03,
       -1.30360937e-02,  4.39856807e-03,  9.27451253e-02,  4.70724776e-02,
        8.62709433e-03,  1.80222013e-03, -1.25161826e-03,  1.32299244e-01,
       -9.92253795e-03, -4.59209224e-03,  1.42861996e-03, -7.23901158e-03,
       -3.13911214e-03, -9.57032945e-03, -1.73183009e-02,  2.45670369e-03,
       -7.96358511e-02, -3.41297314e-03, -4.46015503e-03, -6.39976710e-02,
       -1.25184217e-02,  1.27378833e-02, -1.30528712e-03,  2.73301750e-02,
       -1.21731414e-02, -1.44423349e-02,  7.29520762e-05, -1.22348359e-02,
       -6.50073588e-02, -1.31220510e-02, -1.44033227e-03, -6.31630886e-03,
       -9.22394544e-03, -2.93077645e-03,  5.66824293e-03, -3.54240276e-03,
       -8.12786724e-03, -2.56712176e-02, -6.95126653e-02,  7.63101457e-03,
       -7.92352855e-03,  1.18446136e-02, -1.63575932e-01, -1.09991990e-02,
       -4.90958709e-03,  1.47980615e-01, -2.42481451e-03, -5.43446466e-03,
       -5.99902496e-03, -1.31027857e-02, -8.85262061e-03,  2.62705721e-02,
        2.35932302e-02,  6.05585724e-02,  7.20336149e-03, -1.16878445e-03,
        6.21757843e-03, -7.32720317e-03, -8.18231981e-03,  4.50258255e-02,
        9.44025218e-02, -3.69001110e-03, -1.60129312e-02, -1.14808381e-02,
       -1.12950895e-03, -3.00909299e-03, -4.17287974e-03, -5.02430834e-02,
        3.98692489e-03, -9.71685350e-02, -2.98043154e-02, -1.23281591e-02,
        2.74061668e-03, -5.12612890e-03, -5.07026464e-02, -2.67035346e-02,
       -7.96649382e-02, -2.37052189e-03, -9.88720264e-03, -4.03361693e-02,
        2.11217511e-03, -3.35923280e-03, -6.27897633e-03, -2.99726310e-03,
       -3.82186635e-03,  2.37535941e-03, -9.61404759e-03, -6.83570979e-03,
       -8.27731285e-03,  4.95877452e-02, -4.04350110e-04, -1.01442695e-01,
       -3.45934951e-03, -2.44635902e-02, -1.18905474e-02, -8.10910314e-02,
       -7.18213432e-03, -5.25418930e-02, -2.92874640e-03, -1.10440955e-01,
        1.82822943e-02, -5.09021804e-03, -1.58883131e-03, -3.42267216e-03,
        6.76850695e-03, -1.91351287e-02, -6.30676001e-03, -1.22059658e-02,
       -4.09382582e-03, -6.18315581e-03, -4.64770943e-03, -2.22210097e-03,
       -9.73796938e-03,  4.45719808e-03,  1.96335954e-03, -1.10892290e-02,

In [48]:
import numpy as np

def update_parameters(gpt, params):
    gpt.tok_emb.weight = assign(gpt.tok_emb.weight, params["wte"])
    gpt.pos_emb.weight = assign(gpt.pos_emb.weight, params["wpe"])

    for b in range(len(params["blocks"])):

        q_w, k_w, v_w = np.split((params["blocks"][b]["attn"]["c_attn"])["w"], 3, axis=-1)
        gpt.transformers[b].attention.W_query.weight = assign(gpt.transformers[b].attention.W_query.weight, q_w.T)
        gpt.transformers[b].attention.W_key.weight = assign(gpt.transformers[b].attention.W_key.weight, k_w.T)
        gpt.transformers[b].attention.W_value.weight = assign(gpt.transformers[b].attention.W_value.weight, v_w.T)

        q_b, k_b, v_b = np.split((params["blocks"][b]["attn"]["c_attn"])["b"], 3, axis=-1)
        gpt.transformers[b].attention.W_query.bias = assign(gpt.transformers[b].attention.W_query.bias, q_b)
        gpt.transformers[b].attention.W_key.bias = assign(gpt.transformers[b].attention.W_key.bias, k_b)
        gpt.transformers[b].attention.W_value.bias = assign(gpt.transformers[b].attention.W_value.bias, v_b)

        gpt.transformers[b].attention.out_proj.weight = assign(gpt.transformers[b].attention.out_proj.weight, 
                                                               params["blocks"][b]["attn"]["c_proj"]["w"].T)
        gpt.transformers[b].attention.out_proj.bias = assign(gpt.transformers[b].attention.out_proj.bias,
                                                                params["blocks"][b]["attn"]["c_proj"]["b"])
        
        gpt.transformers[b].ff.layers[0].weight = assign(gpt.transformers[b].ff.layers[0].weight,
                                                          params["blocks"][b]["mlp"]["c_fc"]["w"].T)
        gpt.transformers[b].ff.layers[0].bias = assign(gpt.transformers[b].ff.layers[0].bias,
                                                          params["blocks"][b]["mlp"]["c_fc"]["b"])
        gpt.transformers[b].ff.layers[2].weight = assign(gpt.transformers[b].ff.layers[2].weight,
                                                          params["blocks"][b]["mlp"]["c_proj"]["w"].T)
        gpt.transformers[b].ff.layers[2].bias = assign(gpt.transformers[b].ff.layers[2].bias,
                                                          params["blocks"][b]["mlp"]["c_proj"]["b"])
        
        gpt.transformers[b].norm1.scale = assign(gpt.transformers[b].norm1.scale, params["blocks"][b]["ln_1"]["g"])
        gpt.transformers[b].norm1.shift = assign(gpt.transformers[b].norm1.shift, params["blocks"][b]["ln_1"]["b"])
        gpt.transformers[b].norm2.scale = assign(gpt.transformers[b].norm2.scale, params["blocks"][b]["ln_2"]["g"])
        gpt.transformers[b].norm2.shift = assign(gpt.transformers[b].norm2.shift, params["blocks"][b]["ln_2"]["b"])

    gpt.final_norm.scale = assign(gpt.final_norm.scale, params["g"])
    gpt.final_norm.shift = assign(gpt.final_norm.shift, params["b"])

    gpt.final_output.weight = assign(gpt.final_output.weight, params["wte"])

    return gpt

In [49]:
gpt = update_parameters(gpt, params)
gpt.to(gpu)

GPTModel(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(1024, 768)
  (dropout): Dropout(p=0.1, inplace=False)
  (transformers): Sequential(
    (0): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (1): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (2): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (3): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (4): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (5): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (6): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (7): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (8): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (9): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (10): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (11): TransformerBlock(
      (attention): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (norm1): LayerNormaliztion()
      (norm2): LayerNormaliztion()
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELUActivation()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (final_norm): LayerNormaliztion()
  (final_output): Linear(in_features=768, out_features=50257, bias=False)
)

In [65]:
torch.manual_seed(42)
token_ids = generate_text(
    model = model,
    idx = text_to_token_ids("Every Effort Moves You", tokenizer),
    max_new_tokens=28,
    context_len=GPT_CONFIG_124M["context_length"],
    temperature=1.5,
    topk=50

)

print("Output Text: \n", token_ids_to_text(token_ids, tokenizer))

Output Text:
 Every Effort Moves You for you Stroud rich; and it was arm-room his last word. For Jack Gisburn! Poor women had dropped himself,

In [66]:
torch.manual_seed(42)
token_ids = generate_text(
    model = gpt,
    idx = text_to_token_ids("Every Effort Moves You", tokenizer),
    max_new_tokens=28,
    context_len=NEW_CONFIG_GPT_2["context_length"],
    temperature=1.5,
    topk=50

)

print("Output Text: \n", token_ids_to_text(token_ids, tokenizer))

Output Text:
 Every Effort Moves You To the Table or the Mainstage, and a Better Match Ends Up All Alone For No Good Reason

What if all your efforts failed

Fine Tuning for Spam Classification

Importing, Balancing and Splitting the Dataset

In [7]:
import pandas as pd

spam_df = pd.read_csv("SMSSpamCollection", sep='\t', names=["Label", "Text"])
spam_df

     Label                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [17]:
def create_balanced_dataset(df):

    num_spam = df[df["Label"] == "spam"].shape[0]

    ham_shuffle = df[df["Label"] == "ham"].sample(num_spam, random_state = 123)

    balanced_df = pd.concat([ham_shuffle, df[df["Label"] == "spam"]])

    return balanced_df

In [28]:
balanced_df = create_balanced_dataset(spam_df)
balanced_df["Label"] = balanced_df["Label"].map({"spam":1, "ham":0})
balanced_df

      Label                                               Text
4307      0  Awww dat is sweet! We can think of something t...
4138      0                             Just got to  &lt;#&gt;
4831      0  The word "Checkmate" in chess comes from the P...
4461      0  This is wishing you a great day. Moji told me ...
5440      0      Thank you. do you generally date the brothas?
...     ...                                                ...
5537      1  Want explicit SEX in 30 secs? Ring 02073162414...
5540      1  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547      1  Had your contract mobile 11 Mnths? Latest Moto...
5566      1  REMINDER FROM O2: To get 2.50 pounds free call...
5567      1  This is the 2nd time we have tried 2 contact u...

[1494 rows x 2 columns]

In [25]:
def random_split_dataset(df, train_ratio, val_ratio):
    df = df.sample(frac=1, random_state=123).reset_index(drop=True)

    train_end = int(train_ratio*len(df))
    val_end = train_end + int(val_ratio*len(df))

    train_df = df[:train_end]
    val_df = df[train_end:val_end]
    test_df = df[val_end:]

    return train_df, val_df, test_df

In [26]:
train_df, val_df, test_df = random_split_dataset(balanced_df, 0.7, 0.1)
print(len(train_df))
print(len(val_df))
print(len(test_df))

1045
149
300